### ISSUE TITLE
One nit

### ISSUE THREAD

**Issue by inkredabull** [jgwhite/ember-router-example#1]
Hello,

This project was the first I came across that does a nice job of reducing code demonstrating the Ember Router into a fairly straightforward "Hello World."

One comment I'd have to make it even simpler for others to grok when they land on it is to remove the auth component; dead simple then!  

Cheers and thanks!

Anthony

**Comment by jgwhite** [comment]
Funnily enough, it was actually put together to figure out exactly that: how to automatically transition to a state based on something like authentication.

I take your point though — the name of the repo does suggest a simple router example, and the auth stuff is a more specific solution.
